name: Node CI

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
